# [metadata.heroku]
#   root-package = "github.com/L-oris/go-heroku-continuous_deployment"
#   go-version = "go1.10.3"
#   install = ["."]

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true