defaults: &defaults
    working_directory: /go/src/github.com/L-oris/go-heroku-continuous_deployment
    docker:
        - image: circleci/golang:1.10.3

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run:
                  name: Build
                  command: |
                      dep ensure
                      go build -v
            - persist_to_workspace:
                  # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
                  # taken to be the root directory of the workspace.
                  root: ./
                  # Must be relative path from root
                  paths:
                      - vendor

    test:
        <<: *defaults
        steps:
            - attach_workspace:
                  # Must be absolute path or relative path from working_directory
                  at: ./vendor
            # remove from here
            - run: go get -u github.com/golang/dep/cmd/dep
            - run:
                  name: Build
                  command: |
                      dep ensure
                      go build -v
            # remove to here
            - run:
                  name: Test
                  command: |
                      go fmt ./...
                      go vet ./...
                      go test -v ./...

            # REMOVE ME BEFORE MERGE
            - run:
                  name: Deploy to Heroku
                  command: |
                      mkdir -p ~/.ssh/
                      echo "heroku.com ssh-rsa ${HEROKU_SSH}" >> ~/.ssh/known_hosts
                      echo "StrictHostKeyChecking no" >> ~/.ssh/config
                      git push "git@heroku.com:${HEROKU_APP_NAME}.git" master

    deploy:
        working_directory: /go/src/github.com/L-oris/go-heroku-continuous_deployment
        docker:
            - image: circleci/golang:1.10.3
        steps:
            - checkout
              # remove from here
            - run: go get -u github.com/golang/dep/cmd/dep
            - run:
                  name: Build
                  command: |
                      dep ensure
                      go build -v
            # remove to here
            - run:
                  name: Deploy to Heroku
                  command: |
                      mkdir -p ~/.ssh/
                      echo "heroku.com ssh-rsa ${HEROKU_SSH}" >> ~/.ssh/known_hosts
                      echo "StrictHostKeyChecking no" >> ~/.ssh/config
                      git push "git@heroku.com:${HEROKU_APP_NAME}.git" master

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - test:
                  requires:
                      - build
            - hold:
                  type: approval
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - master
            - deploy:
                  requires:
                      - hold
                  filters:
                      branches:
                          only: master
