version: 2
jobs:
    build:
        working_directory: /go/src/github.com/L-oris/herokuDeploy
        docker:
            - image: circleci/golang:1.10.3
        steps:
            # - run: git config --global url.ssh://git@github.com/your_company.insteadOf https://github.com/your_company
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run:
                  name: Build
                  command: |
                      dep ensure
                      go build -v
            - run:
                  name: Test
                  command: |
                      go fmt ./...
                      go vet ./...
                      go test -v ./...
