version: 2
jobs:
    build:
        working_directory: /go/src/github.com/L-oris/go-heroku-continuous_deployment
        docker:
            - image: circleci/golang:1.10.3
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run:
                  name: Build
                  command: |
                      dep ensure
                      go build -v

    test:
        working_directory: /go/src/github.com/L-oris/go-heroku-continuous_deployment
        docker:
            - image: circleci/golang:1.10.3
        steps:
            - checkout
            - run: go get -u github.com/golang/dep/cmd/dep
            - run:
                  name: Build
                  command: |
                      dep ensure
                      go build -v
            - run:
                  name: Deploy to Heroku
                  command: |
                      mkdir -p ~/.ssh/
                      echo "heroku.com ssh-rsa ${HEROKU_SSH}" >> ~/.ssh/known_hosts
                      echo "StrictHostKeyChecking no" >> ~/.ssh/config
                      git push "git@heroku.com:${HEROKU_APP_NAME}.git" master

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - test:
                  requires:
                      - build
